---
version: '3'
services:
  http-proxy:
    build:
      context: ./aio
    env_file:
      - .env
    environment:
      - CURRENT_COLOR=green
      - NEXT_COLOR=blue
    networks:
      - api-search-annuaire-entreprises
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiosearch.rule=Host(`localhost`)"
      - "traefik.http.routers.aiosearch.entrypoints=aiosearch"
      - "traefik.port=4500"
    container_name: aio-green
networks:
  api-search-annuaire-entreprises:
    name: api-search-annuaire-entreprises
