name: Test Search API
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [ 3.8.8 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}
          restore-keys: build-${{ env.pythonLocation }}-${{ matrix.os }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aio/aio-proxy/requirements.pip

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.8.8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}
      - name: unit tests
        run: |
          cd aio/aio-proxy
          pytest -v  

  lint-files:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false # Only new or edited files
          VALIDATE_JSCPD: false # Copy/paste detection
          VALIDATE_GITHUB_ACTIONS: false # Due to shellcheck SC2086 issues
          VALIDATE_MARKDOWN: false # Due to multiple headings issue
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_HTML: false
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
